#!/usr/bin/env python3
"""report.py — zero-maintenance coverage dashboard.

Two responsibilities, matching docs/blog/nightly-qa-agent.md:

  append   Append (or replace) today's row in docs/reports/coverage_history.csv
  render   Regenerate docs/reports/coverage_dashboard.md from that CSV

The dashboard is a plain Markdown file (table + text progress chart) that the
team can read straight in the repo — no database, no hosted service.

Usage:
  python3 scripts/report.py append --date 2026-06-13 --coverage 71.2 \\
      --tests 3 --runtime 540
  python3 scripts/report.py render
"""
from __future__ import annotations

import argparse
import csv
import os
from pathlib import Path

REPORTS_DIR = Path(__file__).resolve().parent.parent / "docs" / "reports"
CSV_PATH = REPORTS_DIR / "coverage_history.csv"
DASHBOARD_PATH = REPORTS_DIR / "coverage_dashboard.md"
HEADER = ["date", "coverage_pct", "tests_added", "run_time_sec"]


def _read_rows() -> list[dict]:
    if not CSV_PATH.exists():
        return []
    with CSV_PATH.open(newline="") as fh:
        return [row for row in csv.DictReader(fh)]


def _write_rows(rows: list[dict]) -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    rows.sort(key=lambda r: r["date"])
    with CSV_PATH.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=HEADER)
        writer.writeheader()
        writer.writerows(rows)


def append(date: str, coverage: float, tests: int, runtime: int) -> None:
    rows = [r for r in _read_rows() if r["date"] != date]  # replace same-day run
    rows.append(
        {
            "date": date,
            "coverage_pct": f"{coverage:.1f}",
            "tests_added": str(tests),
            "run_time_sec": str(runtime),
        }
    )
    _write_rows(rows)
    print(f"Recorded {date}: {coverage:.1f}% coverage, {tests} tests, {runtime}s")


def _bar(pct: float, width: int = 24) -> str:
    filled = round(pct / 100 * width)
    return "█" * filled + "░" * (width - filled)


def _fmt_runtime(seconds: int) -> str:
    m, s = divmod(seconds, 60)
    return f"{m}m{s:02d}s" if m else f"{s}s"


def render() -> None:
    rows = _read_rows()
    lines: list[str] = []
    lines.append("# Nightly QA — Coverage Dashboard")
    lines.append("")
    lines.append("> Auto-generated by `scripts/report.py render`. Do not edit by hand.")
    lines.append("")

    if not rows:
        lines.append("_No runs recorded yet._")
        DASHBOARD_PATH.write_text("\n".join(lines) + "\n")
        print(f"Wrote {DASHBOARD_PATH} (empty)")
        return

    latest = rows[-1]
    first = rows[0]
    delta = float(latest["coverage_pct"]) - float(first["coverage_pct"])
    lines.append(
        f"**Latest:** {latest['coverage_pct']}% coverage "
        f"({'+' if delta >= 0 else ''}{delta:.1f}% since {first['date']}) "
        f"· {len(rows)} runs recorded"
    )
    lines.append("")

    # Trend chart
    lines.append("## Coverage trend")
    lines.append("")
    lines.append("```")
    for r in rows:
        pct = float(r["coverage_pct"])
        lines.append(f"{r['date']}  {_bar(pct)} {pct:5.1f}%")
    lines.append("```")
    lines.append("")

    # History table
    lines.append("## Run history")
    lines.append("")
    lines.append("| Date | Coverage | Δ vs prev | Tests added | Run time |")
    lines.append("|------|----------|-----------|-------------|----------|")
    prev = None
    for r in rows:
        pct = float(r["coverage_pct"])
        d = "—" if prev is None else f"{'+' if pct - prev >= 0 else ''}{pct - prev:.1f}%"
        lines.append(
            f"| {r['date']} | {pct:.1f}% | {d} | {r['tests_added']} | "
            f"{_fmt_runtime(int(r['run_time_sec']))} |"
        )
        prev = pct
    lines.append("")

    DASHBOARD_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {DASHBOARD_PATH} ({len(rows)} runs)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_append = sub.add_parser("append", help="record today's run, then re-render")
    p_append.add_argument("--date", required=True)
    p_append.add_argument("--coverage", type=float, required=True)
    p_append.add_argument("--tests", type=int, default=0)
    p_append.add_argument("--runtime", type=int, default=0)

    sub.add_parser("render", help="regenerate the dashboard from the CSV")

    args = parser.parse_args()
    if args.cmd == "append":
        append(args.date, args.coverage, args.tests, args.runtime)
        render()
    elif args.cmd == "render":
        render()


if __name__ == "__main__":
    main()
